/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StarComponent {
    'fill': string;
    'height': number;
    'longR': number;
    'rotate': number;
    'shortR': number;
    'stroke': string;
    'svgStyle': string;
    'width': number;
    'x': number;
    'y': number;
  }
  interface StarComponentAttributes extends StencilHTMLAttributes {
    'fill'?: string;
    'height'?: number;
    'longR'?: number;
    'rotate'?: number;
    'shortR'?: number;
    'stroke'?: string;
    'svgStyle'?: string;
    'width'?: number;
    'x'?: number;
    'y'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StarComponent': Components.StarComponent;
  }

  interface StencilIntrinsicElements {
    'star-component': Components.StarComponentAttributes;
  }


  interface HTMLStarComponentElement extends Components.StarComponent, HTMLStencilElement {}
  var HTMLStarComponentElement: {
    prototype: HTMLStarComponentElement;
    new (): HTMLStarComponentElement;
  };

  interface HTMLElementTagNameMap {
    'star-component': HTMLStarComponentElement
  }

  interface ElementTagNameMap {
    'star-component': HTMLStarComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
